modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL = "https://github.com/Hunter19823/KubeJSTwitchIntegration/issues"
license = "All Rights Reserved"

[[mods]]
modId="kubejstwitchintegration"
version="${file.jarVersion}"
displayName="KubeJS Twitch4j Integration"
logoFile="KubeJSIcon.png"
authors="ILIKEPIEFOO2"
description='''
KubeJS Twitch4j Integration.
Full list of events can be found here:
https://github.com/Hunter19823/KubeJSTwitchIntegration/blob/master/src/main/java/pie/ilikepiefoo2/kubejstwitchintegration/KubeJSEvents.java
Example Scripts can be found:
https://github.com/Hunter19823/KubeJSTwitchIntegration/tree/master/src/test/resources
'''

[[dependencies.kubejstwitchintegration]]
           modId="forge"
           mandatory = true
           versionRange = "[35,)"
           ordering = "NONE"
           side="BOTH"

[[dependencies.kubejstwitchintegration]]
           modId="twitchintegration"
           mandatory = true
           versionRange = "[1.0.4,)"
           ordering = "AFTER"
           side="BOTH"

[[dependencies.kubejstwitchintegration]]
            modId="kubejs"
            mandatory = true
            versionRange = "[1603,)"
            ordering = "AFTER"
            side="BOTH"
